### ISSUE TITLE
Nix build down - cachix 404

### ISSUE THREAD

**Issue by soywod** [soywod/himalaya#184]
@toastal any idea?

```
installer options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve --daemon --daemon-user-count 4 --no-channel-add --darwin-use-unencrypted-nix-store-volume --nix-extra-conf-file /tmp/nix.conf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     77      0 --:--:-- --:--:-- --:--:--    77
/dev/fd/63: 1: 404: not found
child_process.js:642
    throw err;
    ^

Error: Command failed: /home/runner/work/_actions/cachix/install-nix-action/v13/lib/install-nix.sh
    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at Object.<anonymous> (/home/runner/work/_actions/cachix/install-nix-action/v13/lib/main.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 1594,
  stdout: null,
  stderr: null
}
```

**Comment by toastal** [comment]
Try rekicking the servers later. Cachix has been having intermittent issues because Cloudflare is trash.

**Comment by soywod** [comment]
@toastal the problem is still there, I doubt it is still because of Cloudflare crash?

**Comment by toastal** [comment]
I have no idea what the Cachix action does or how any of that works. It's definitely 404ing. I've had no issues building locally though.

**Comment by soywod** [comment]
In fact it is this path that is not found: https://github.com/soywod/himalaya/blob/f92bd62e899ce270f667d921b8b8cac7e29a7340/.github/workflows/nix-build.yaml#L16. What does it refer to?

**Comment by toastal** [comment]
I have no idea. I've never ran GitHub CI.

**Comment by soywod** [comment]
Fixed by updating the `install_url` link.

**Comment by toastal** [comment]
Awesome. Good to hear you figured out a solution, man! If this weren't a GitHub CI-specific issue, I would have been more inclined to check it out. My Nix CI experience right now is minimal and only with Sourcehut.

**Comment by soywod** [comment]
Don't worry it's fine, you already helped a lot on this project :wink:
